### PR TITLE
Fix: Handle window size in native layer

### LINKED ISSUE #79: BugReport | `MaxHeight` `MinHeight` `MaxWidth` `MaxWidth` should retreive their values from the native side and not store them locally in C#
### 📝 Bug Description

Currently InfiniFrame holds the values of a Window's `MaxHeight` `MinHeight` `MaxWidth` `MaxWidth` in C# managed memory, whilst it is already stored and managed on the C++ side. Like all other properties that are handled by the C++ Native code, these values should not managed by C# and only referenced.

### 🧐 Expected Behavior

_No response_

### 🔄 Steps to Reproduce

_No response_

### 🖥 Browser/OS Information

_No response_

### 📐 Application Section

🔗 API

### PR DESCRIPTION
**Pull request by freakdaniel**
## Description
This PR fixes the window size constraint properties so `MaxHeight`, `MaxWidth`, `MinHeight`, and `MinWidth` are retrieved from the native layer instead of being stored separately in managed C# state

## Type of Change

- [x] Bug fix (non-breaking change fixing an issue)

## Changes Made

- Added native `GetMaxSize` and `GetMinSize` APIs and wired them through the export and C# interop layers
- Updated `InfiniFrameWindow` to read min/max size constraints from native state, with startup parameter fallback before initialization
- Removed managed-side caching of min/max window size constraints from the window builder and window extension methods
- Implemented native min/max size getters for Windows, Linux, and macOS, and ensured Linux keeps its internal constraint values in sync when setters are called

## Related Issues
Closes #79

## Checklist

- [x] My code follows the project's coding standards
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the documentation accordingly
- [x] My changes generate no new warnings
- [x] All tests pass locally
- [x] I have added tests that prove my fix/feature works
- [x] New and existing unit tests pass locally
- [x] Any dependent changes have been merged and published

### CODE REVIEW

File: src/InfiniFrame/InfiniFrameWindow.cs [hunk 1]
```diff
@@ -635,18 +635,46 @@ public IntPtr OnCustomScheme(string url, out int numBytes, out string? contentTy
 
     ///<summary>Gets or set the maximum size of the native window in pixels.</summary>
     public Size MaxSize {
-        get => new(MaxWidth, MaxHeight);
+        get => InstanceHandle == IntPtr.Zero
```
Comment (AnnaSasDev) [inline src/InfiniFrame/InfiniFrameWindow.cs]: constantly checking for `InstanceHandle == IntPtr.Zero` is the old way how Photino did it, as they had window setup and window usage functionality in the same class.

The should be alligned with the rest of the properties and have their set logic done through the FLUENT API extensions.

Comment (AnnaSasDev) [reply src/InfiniFrame/InfiniFrameWindow.cs]: I know this is an API regression, but in this case it makes the most sense, as it now adheres to all the other properties that exist on the window directly

**Review by AnnaSasDev — APPROVED** [review]
